# Change these first
owner: Deep-Ads # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Site
    url: https://www.deepads.com.br
    expectedStatusCodes:
      - 200
      - 201
      - 403
      - 401
      - 400
      - 503
  - name: Painel do Cliente
    url: https://app.deepads.com.br
    expectedStatusCodes:
      - 200
      - 201
      - 403
      - 401
      - 400
      - 503
  - name: Campanhas
    url: https://lancamento.deepads.com.br
    expectedStatusCodes:
      - 200
      - 201
      - 403
      - 401
      - 400
      - 503
  - name: Whatsapp EUA-01
    url: https://wpp-01.deepads.com.br
    expectedStatusCodes:
      - 200
      - 201
      - 403
      - 401
      - 400
      - 503

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.deepads.com.br
  # baseUrl: /your-repo-name
  logoUrl: https://www.deepads.com.br/wp-content/uploads/elementor/thumbs/logo_horizontal@2x-p5r2vu6c2oc21xhugymxs2lw4xsdum52fbqcl530u8.png
  name: Deep Ads
  introTitle: "**Deep Ads**, a melhor plataforma para lançamentos integrados com o Whatsapp."
  introMessage: Verifique os status de nossos serviços
  navbar:
    - title: Status
      href: /
    - title: Login
      href: https://app.deepads.com.br
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
